name: Lint and Build

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Type check
        run: pnpm tsc --noEmit

      - name: Lint web app
        run: |
          cd apps/web
          pnpm run lint || echo "No lint script found for web app"

      - name: Lint API app
        run: |
          cd apps/api
          pnpm run lint || echo "No lint script found for API app"

      - name: Lint marketing app
        run: |
          cd apps/marketing
          pnpm run lint || echo "No lint script found for marketing app"

      - name: Build web app
        run: |
          cd apps/web
          pnpm run build

      - name: Build API app
        run: |
          cd apps/api
          pnpm run build

      - name: Build marketing app
        run: |
          cd apps/marketing
          pnpm run build

      - name: Build UI package
        run: |
          cd packages/ui
          pnpm run build || echo "No build script found for UI package"

      - name: Build DB package
        run: |
          cd packages/db
          pnpm run build || echo "No build script found for DB package"

      - name: Build Common package
        run: |
          cd packages/common
          pnpm run build || echo "No build script found for Common package"

      - name: Build Sandbox SDK package
        run: |
          cd packages/sandbox-sdk
          pnpm run build || echo "No build script found for Sandbox SDK package"
